CREATE TABLE PLAYERS (
	P_PLAYERKEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	P_PNAME VARCHAR(128) NOT NULL,
	P_PASS BINARY(60) NOT NULL)

CREATE TABLE CAMPAIGN(
	C_CAMKEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_NAME 	 VARCHAR(128) NOT NULL,
	C_DM	INT NOT NULL)

CREATE TABLE CHARACTERS(
	C_CHARKEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	C_CNUM INT NOT NULL,
	C_CREATOR INT NOT NULL,  
	C_CHARNAME VARCHAR(128) NOT NULL,
	C_LA INT NOT NULL,
	C_HPMAX INT NOT NULL,
	C_HPCURR INT NOT NULL,
	C_RACE VARCHAR(128) NOT NULL,
	C_MINI VARCHAR(128),
	C_STR INT NOT NULL,
	C_DEX INT NOT NULL,
	C_CON INT NOT NULL,
	C_INT INT NOT NULL,
	C_WIS INT NOT NULL,
	C_CHA INT NOT NULL)

CREATE TABLE INVENTORY(
	)

CREATE TABLE CLASSES()

CREATE TABLE STATUS()

CREATE TABLE NPC()

CREATE TABLE SKILLS()
	