CREATE TABLE PLAYERS (
	PLAYER_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PLAYER_NAME VARCHAR(128) NOT NULL,
	PLAYER_PASS BINARY(60) NOT NULL,
	PLAYER_EMAIL VARCHAR(128) NOT NULL)

//NOT DONE
CREATE TABLE ALLSTATUS()

//NOT DONE
CREATE TABLE ALLSKILLS()

//NOT DONE
CREATE TABLE ALLCLASSES()

//NOT DONE
CREATE TABLE ALLFEATS()

//NOT DONE
CREATE TABLE ALLSPELLS()

//NOT DONE
CREATE TABLE ALLSLA()

//NOT DONE
CREATE TABLE SPECIAL()

CREATE TABLE ITEMS(
	ITEM_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ITEM_INAME VARCHAR(128) NOT NULL,
	ITEM_IDESRIPT VARCHAR(512),
	ITEM_COST VARCHAR(128),
	ITEM_TYPE INT,
	ITEM_WEAPSIZE INT,
	ITEM_WEAPDMG INT,
	ITEM_RANGE INT,
	ITEM_MAGIC INT,
	ITEM_LBS DECIMAL(15,2),
	ITEM_QUANTITY INT,
	ITEM_WRITER INT NOT NULL,
	ITEM_SOURCE INT NOT NULL)

///NOT DONE
CREATE TABLE MAGIC()

CREATE TABLE ITEMTYPES(
	I_TYPEKEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	I_TYPENAME VARCHAR(128) NOT NULL,
	I_TYPESIZE VARCHAR(16),
	I_TYPEDMG VARCHAR(64),
	I_DMGTYPE VARCHAR(64),
	I_TYPERANGE INT)

CREATE TABLE CAMPAIGN(
	CAM_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CAM_NAME 	 VARCHAR(128) NOT NULL,
	CAM_DM	INT NOT NULL)

CREATE TABLE CHARACTERS(
	CHAR_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CHAR_CAMPAIGNNUM INT NOT NULL,
	CHAR_CREATOR INT NOT NULL,
	CHAR_NAME VARCHAR(128) NOT NULL,
	CHAR_LA INT NOT NULL,
	CHAR_HPMAX INT NOT NULL,
	CHAR_HPCURR INT NOT NULL,
	CHAR_MINI VARCHAR(128),
	CHAR_STR INT NOT NULL,
	CHAR_DEX INT NOT NULL,
	CHAR_CON INT NOT NULL,
	CHAR_INT INT NOT NULL,
	CHAR_WIS INT NOT NULL,
	CHAR_CHA INT NOT NULL)

CREATE TABLE NPC(
	NPC_CHARKEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NPC_CAMPAIGNNUM INT NOT NULL,
	NPC_CREATOR INT NOT NULL,
	NPC_CHARNAME VARCHAR(128) NOT NULL,
	NPC_LA INT NOT NULL,
	NPC_HPMAX INT NOT NULL,
	NPC_HPCURR INT NOT NULL,
	NPC_MINI VARCHAR(128),
	NPC_STR INT NOT NULL,
	NPC_DEX INT NOT NULL,
	NPC_CON INT NOT NULL,
	NPC_INT INT NOT NULL,
	NPC_WIS INT NOT NULL,
	NPC_CHA INT NOT NULL)

//NOT DONE
CREATE TABLE RACES(
	R_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	R_RACE VARCHAR(128),
	R_LORE MEDIUMTEXT,
	R_CREATOR INT NOT NULL,
	R_SOURCE INT NOT NULL,
)

//NOT DONE
CREATE TABLE FEATS()

CREATE TABLE INVENTORY(
	INV_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	INV_CHARKEY INT NOT NULL,
	INV_ITEMKEY INT NOT NULL,
	INV_QUANTITY INT NOT NULL)

CREATE TABLE CLASSES(
	CLASS_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CLASS_CHARKEY INT NOT NULL,
	CLASS_CLASSKEY INT NOT NULL,
	CLASS_QUANTITY INT NOT NULL)

CREATE TABLE STATUS(
	STATUS_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	STATUS_NAME INT NOT NULL,
	STATUS_CHARKEY INT NOT NULL,
	STATUS_DURATION INT NOT NULL)

CREATE TABLE SKILLS(
	SKILL_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SKILL_NAME INT NOT NULL,
	SKILL_CHKEY INT NOT NULL,
	SKILL_QUANTITY INT NOT NULL)

CREATE TABLE SOURCES(
	SOURCE_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SOURCE_NAME VARCHAR(128) NOT NULL)
