--01 - Top level relation
CREATE TABLE PLAYERS (
	PLAYER_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PLAYER_NAME VARCHAR(128) NOT NULL,
	PLAYER_PASS BINARY(60) NOT NULL,
	PLAYER_EMAIL VARCHAR(128) NOT NULL)

CREATE TABLE ALLSTATUS(
	ALLSTATUS_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	STATUS_NAME VARCHAR(128) NOT NULL,
	STATUS_TYPE VARCHAR(64) NOT NULL,
	STATUS_DESCRIPTION VARCHAR(1024) NOT NULL,
	STATUS_EFFECTS VARCHAR(1024) NOT NULL,
	STATUS_HIDDEN VARCHAR(1024),
	STATUS_WRITER INT NOT NULL,
	STATUS_SOURCE INT NOT NULL)

CREATE TABLE ALLSKILLS(
	ALLSKILLS_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ALLSKILLS_NAME VARCHAR(128) NOT NULL,
	ALLSKILLS_STAT INT NOT NULL,
	ALLSKILLS_CHECKPENALTY CHAR(8) NOT NULL,
	ALLSKILLS_DESCRIPTION VARCHAR(2048) NOT NULL,
	ALLSKILLS_SYNERGY INT NOT NULL,
	ALLSKILLS_BONUS VARCHAR(16) NOT NULL)

CREATE TABLE ALLCLASSES(
	ALLCLASSES_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ALLCLASSES_NAME VARCHAR(128) NOT NULL,
	ALLCLASSES_DESCRIPTION VARCHAR(16384) NOT NULL,
	ALLCLASSES_CASTSTAT INT,
	ALLCLASSES_CASTTYPE VARCHAR(64),
	ALLCLASSES_TYPE VARCHAR(64) NOT NULL,
	ALLCLASSES_KEYWORDS VARCHAR(2048) NOT NULL,
	ALLCLASSES_PRESTIGE BOOLEAN NOT NULL,
	ALLCLASSES_REQUIREMENTS VARCHAR(1024) NOT NULL,
	ALLCLASSES_ALIGNMENT VARCHAR(32) NOT NULL,
	ALLCLASSES_HITDIE VARCHAR(8) NOT NULL,
	ALLCLASSES_SKILLS VARCHAR(1024) NOT NULL,
	ALLCLASSES_SKILLPOINTS VARCHAR(64) NOT NULL,
	ALLCLASSES_ADVANCEMENT VARCHAR(16384) NOT NULL,
	ALLCLASSES_HIDDEN VARCHAR(1024),
	ALLCLASSES_WRITER INT NOT NULL,
	ALLCLASSES_SOURCE INT NOT NULL)

CREATE TABLE ALLFEATS(
	ALLFEATS_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ALLFEATS_NAME VARCHAR(128) NOT NULL,
	ALLFEATS_DESCRIPTION VARCHAR(16384) NOT NULL,
	ALLFEATS_TYPE VARCHAR(64) NOT NULL,
	ALLFEATS_KEYWORDS VARCHAR(2048) NOT NULL,
	ALLFEATS_BENEFIT VARCHAR(1024) NOT NULL,
	ALLFEATS_NORMAL VARCHAR(1024) NOT NULL,
	ALLFEATS_SPECIAL VARCHAR(1024) NOT NULL,
	ALLFEATS_REQUIREMENTS VARCHAR(1024) NOT NULL,
	ALLFEATS_HIDDEN VARCHAR(1024),
	ALLFEATS_WRITER INT NOT NULL,
	ALLFEATS_SOURCE INT NOT NULL)

CREATE TABLE ALLSPELLS(
	ALLSPELLS_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ALLSPELLS_NAME VARCHAR(64) NOT NULL,
	ALLSPELLS_SCHOOL VARCHAR(64) NOT NULL,
	ALLSPELLS_TYPE VARCHAR(64) NOT NULL,
	ALLSPELLS_REQUIREMENT VARCHAR(1024) NOT NULL,
	ALLSPELLS_COMPONENTS VARCHAR(128) NOT NULL,
	ALLSPELLS_CASTING VARCHAR(128) NOT NULL,
	ALLSPELLS_RANGE VARCHAR(128) NOT NULL,
	ALLSPELLS_EFFECT VARCHAR(128) NOT NULL,
	ALLSPELLS_DURATION VARCHAR(128) NOT NULL,
	ALLSPELLS_SAVE VARCHAR(128) NOT NULL,
	ALLSPELLS_RESISTANCE VARCHAR(128) NOT NULL,
	ALLSPELLS_DESCRIPTION VARCHAR(1024) NOT NULL,
	ALLSPELLS_HIDDEN VARCHAR(1024),
	ALLSPELLS_WRITER INT NOT NULL,
	ALLSPELLS_SOURCE INT NOT NULL)

CREATE TABLE ALLABILITIES(
	ALLABILITIES_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ALLABILITIES_NAME VARCHAR(64) NOT NULL,
	ALLABILITIES_TYPE VARCHAR(64) NOT NULL,
	ALLABILITIES_SPELL INT,
	ALLABILITIES_DESCRIPTION VARCHAR(16384) NOT NULL,
	ALLABILITIES_HIDDEN VARCHAR(1024),
	ALLABILITIES_WRITER INT NOT NULL,
	ALLABILITIES_SOURCE INT NOT NULL)

--NOT DONE
CREATE TABLE ITEMS(
	ITEM_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	--GreatSword \ Pearl of Power (1st)
	ITEM_INAME VARCHAR(256) NOT NULL,
	--Big fucking sword \ Able to recall first level spells
	ITEM_IDESRIPT VARCHAR(8192),
	--100g \ 1000g
	ITEM_COST VARCHAR(128),
	--Two-handed Melee Weapon \ Wonderous Item
	ITEM_TYPE VARCHAR(64),
	--Medium \ N/A
	ITEM_WEAPSIZE VARCHAR(32),
	--2D6 SLASHING\ N/A
	ITEM_WEAPDMG VARCHAR(64),
	--MELEE \ PERSONAL
	ITEM_RANGE VARCHAR(64),
	--N/A \ CASTER LEVEL 7
	ITEM_MAGIC VARCHAR(64),
	--5LBS \ 0.1LBS
	ITEM_LBS DECIMAL(15,2),
	--N/A \ 1/DAY
	ITEM_USES VARCHAR(64),
	ITEM_HIDDEN VARCHAR(1024),
	ITEM_WRITER INT NOT NULL,
	ITEM_SOURCE INT NOT NULL)

CREATE TABLE CAMPAIGN(
	CAM_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CAM_NAME VARCHAR(128) NOT NULL,
	CAM_DM	INT NOT NULL)

CREATE TABLE CHARACTERS(
	CHAR_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CHAR_CAMPAIGNNUM INT NOT NULL,
	CHAR_CREATOR INT NOT NULL,
	CHAR_NAME VARCHAR(128) NOT NULL,
	CHAR_DESCRIPTION VARCHAR(16384),
	CHAR_RACE INT NOT NULL,
	CHAR_EXP INT NOT NULL,
	CHAR_HPMAX INT NOT NULL,
	CHAR_HPCURR INT NOT NULL,
	CHAR_MINI VARCHAR(128),
	CHAR_STR INT NOT NULL,
	CHAR_DEX INT NOT NULL,
	CHAR_CON INT NOT NULL,
	CHAR_INT INT NOT NULL,
	CHAR_WIS INT NOT NULL,
	CHAR_CHA INT NOT NULL)

CREATE TABLE NPC(
	NPC_CHARKEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NPC_CAMPAIGNNUM INT NOT NULL,
	NPC_CREATOR INT NOT NULL,
	NPC_CHARNAME VARCHAR(128) NOT NULL,
	NPC_DESCRIPTION VARCHAR(16384),
	NPC_RACE INT NOT NULL,
	NPC_EXP INT NOT NULL,
	NPC_HPMAX INT NOT NULL,
	NPC_HPCURR INT NOT NULL,
	NPC_MINI VARCHAR(128),
	NPC_STR INT NOT NULL,
	NPC_DEX INT NOT NULL,
	NPC_CON INT NOT NULL,
	NPC_INT INT NOT NULL,
	NPC_WIS INT NOT NULL,
	NPC_CHA INT NOT NULL,
	NPC_HIDDEN VARCHAR(1024) NOT NULL)

CREATE TABLE ALLMONSTERS(
	AM_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	AM_CAMPAIGNNUM INT NOT NULL,
	AM_NAME VARCHAR(128) NOT NULL,
	AM_TYPE VARCHAR(128) NOT NULL,
	AM_SIZE VARCHAR(128) NOT NULL,
	AM_SPEED VARCHAR(128) NOT NULL,
	AM_HITDICE VARCHAR(128) NOT NULL,
	AM_CR VARCHAR(128) NOT NULL,
	AM_ENVIRONMENT VARCHAR(256) NOT NULL,
	AM_ALIGNMENT VARCHAR(128) NOT NULL,
	AM_DESCRIPTION VARCHAR(16384) NOT NULL,
	AM_KNOWLEDGE VARCHAR(1024),
	AM_SEEN BOOLEAN,
	AM_HIDDEN VARCHAR(1024) NOT NULL,
	AM_WRITER INT NOT NULL,
	AM_SOURCE INT NOT NULL)

CREATE TABLE MONSTERS(
	M_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	M_NOTES VARCHAR(8192))

CREATE TABLE ALLTEMPLATES(
	TEM_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TEM_CAMPAIGNNUM INT NOT NULL,
	TEM_NAME VARCHAR(256),
	TEM_LA INT NOT NULL,
	TEM_ATTRIBUTES VARCHAR(1024),
	TEM_LORE VARCHAR(16384),
	TEM_IMAGE VARCHAR(1024),
	TEM_LAYOUT VARCHAR(1024),
	TEM_HIDDEN VARCHAR(1024) NOT NULL,
	TEM_WRITER INT NOT NULL,
	TEM_SOURCE INT NOT NULL)

CREATE TABLE TEMPLATES(
	T_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	T_TEMPLATE INT NOT NULL,
	T_CHARKEY INT NOT NULL,
	T_NOTES VARCHAR(1024))

CREATE TABLE RACES(
	R_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	R_CAMPAIGNNUM INT NOT NULL,
	R_RACE VARCHAR(256),
	R_LA INT NOT NULL,
	R_ATTRIBUTES VARCHAR(16384),
	R_LORE VARCHAR(16384),
	R_IMAGE VARCHAR(1024),
	R_LAYOUT VARCHAR(1024),
	R_HIDDEN VARCHAR(1024) NOT NULL,
	R_WRITER INT NOT NULL,
	R_SOURCE INT NOT NULL)

CREATE TABLE FEATS(
	FEAT_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FEAT_FEAT INT NOT NULL,
	FEAT_CHARKEY INT NOT NULL,
	FEAT_NOTES VARCHAR(256))

CREATE TABLE INVENTORY(
	INV_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	INV_CHARACTERKEY INT NOT NULL,
	INV_ITEMKEY INT NOT NULL,
	INV_QUANTITY INT NOT NULL,
	INV_NOTES VARCHAR(256))

CREATE TABLE CLASSES(
	CLASS_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CLASS_CHARKEY INT NOT NULL,
	CLASS_CLASSKEY INT NOT NULL,
	CLASS_QUANTITY INT NOT NULL)

CREATE TABLE STATUS(
	STATUS_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	STATUS_STATUS INT NOT NULL,
	STATUS_CHARKEY INT NOT NULL,
	STATUS_DURATION INT NOT NULL)

CREATE TABLE SKILLS(
	SKILL_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SKILL_SKILL INT NOT NULL,
	SKILL_CHARKEY INT NOT NULL,
	SKILL_QUANTITY INT NOT NULL)

CREATE TABLE SPELLS(
	SPELL_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SPELLS_CHARKEY INT NOT NULL,
	SPELLS_SPELL INT NOT NULL)

	CREATE TABLE ABILITIES(
		A_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
		A_ABILITY INT NOT NULL,
		A_CHARKEY INT NOT NULL,
		A_USAGE VARCHAR(256))

CREATE TABLE SOURCES(
	SOURCE_KEY INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SOURCE_NAME VARCHAR(256) NOT NULL)
